FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR "/src"

COPY *.sln .
COPY WebApi/*.csproj ./WebApi/
COPY Infrastructure/*.csproj ./Infrastructure/
COPY Application/*.csproj ./Application/
COPY Domain/*.csproj ./Domain/

RUN dotnet restore


COPY . .
WORKDIR /src/WebApi
RUN dotnet build "WebApi.csproj" -c Release -o /app/build


FROM build AS publish
RUN dotnet publish "WebApi.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .


EXPOSE 8080


ENTRYPOINT ["dotnet", "WebApi.dll"]